name: Deploy to Netlify

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: npm install
      - run: npm run build

      - run: ls -a

      - name: Publish
        uses: netlify/actions/cli@master
        with:
          args: deploy --dir=dist --debug --prod
        env:
          NETLIFY_SITE_ID: ${{ secrets.SITE_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
